//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cldvPOE_st10081893.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class st10081893cldvEntities : DbContext
    {
        public st10081893cldvEntities()
            : base("name=st10081893cldvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authorisedInspector> authorisedInspectors { get; set; }
        public virtual DbSet<tbl_bodyType> tbl_bodyType { get; set; }
        public virtual DbSet<tbl_car> tbl_car { get; set; }
        public virtual DbSet<tbl_driver> tbl_driver { get; set; }
        public virtual DbSet<tbl_inspector> tbl_inspector { get; set; }
        public virtual DbSet<tbl_manufacturer> tbl_manufacturer { get; set; }
        public virtual DbSet<tbl_modelInfo> tbl_modelInfo { get; set; }
        public virtual DbSet<tbl_person> tbl_person { get; set; }
        public virtual DbSet<tbl_rental> tbl_rental { get; set; }
        public virtual DbSet<tbl_returns> tbl_returns { get; set; }
    
        public virtual ObjectResult<Nullable<int>> calculateFine(Nullable<int> rentalID)
        {
            var rentalIDParameter = rentalID.HasValue ?
                new ObjectParameter("rentalID", rentalID) :
                new ObjectParameter("rentalID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("calculateFine", rentalIDParameter);
        }
    }
}
